[merge]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
[diff]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Target }}"]

[edit]
command = "nvim"

[git]
autoCommit = true

[onepassword]
mode = "service"

